apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: masterannonce
type: Opaque
data:
  # Base64 encoded values (echo -n 'value' | base64)
  POSTGRES_DB: TWFzdGVyQW5ub25jZQ==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: Y2hhbmdlX21l
  SEED_DEFAULT_PASSWORD: cGFzc3dvcmQxMjM=
