-- Schema JPA/Hibernate pour MasterAnnonce
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Table Roles (RBAC dynamique)
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Table Users
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Autorites rattachees aux roles
CREATE TABLE IF NOT EXISTS role_authorities (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    authority VARCHAR(64) NOT NULL,
    PRIMARY KEY (role_id, authority)
);

-- Table Category
CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(100) NOT NULL UNIQUE
);

-- Table Annonce
CREATE TABLE IF NOT EXISTS annonce (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(64) NOT NULL,
    description VARCHAR(256) NOT NULL,
    adress VARCHAR(64) NOT NULL,
    mail VARCHAR(64) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    author_id UUID NOT NULL REFERENCES users(id),
    category_id BIGINT NOT NULL REFERENCES category(id)
);

-- Index pour les recherches
CREATE INDEX IF NOT EXISTS idx_annonce_status ON annonce(status);
CREATE INDEX IF NOT EXISTS idx_annonce_date ON annonce(date DESC);
CREATE INDEX IF NOT EXISTS idx_annonce_author ON annonce(author_id);
CREATE INDEX IF NOT EXISTS idx_annonce_category ON annonce(category_id);
